# Whisper
DEFAULT_WHISPER_MODEL = "base"
DEFAULT_WHISPER_LANGUAGE = "auto"
DEFAULT_WHISPER_TRANSLATE = False
DEFAULT_WHISPER_TEMPERATURE = 0.0

# Download
DEFAULT_DOWNLOAD_FORMAT = "bestaudio/best"
DEFAULT_DOWNLOAD_CODEC = "mp3"
DEFAULT_SOCKET_TIMEOUT = 30
DEFAULT_RETRIES = 3
DEFAULT_RETRY_BACKOFF = 2.0

# Output
DEFAULT_OUTPUT_DIRECTORY = "./output"
DEFAULT_OUTPUT_FORMAT = "txt"
DEFAULT_SANITIZE_FILENAMES = True
DEFAULT_ON_EXISTING = "skip"

# Logging
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_LOG_FILE = None
DEFAULT_LOG_ROTATION = "10 MB"

# Config
DEFAULT_CONFIG_PATH = "config/default.yaml"
